Repository gitovep/gitove, pull requests merged in 2023-08, with the labels that each got.

#8 Basic Git Command Wrap
  package.json
  pnpm-lock.yaml
  src/commands/execution/command.ts
  src/commands/execution/git_wrap.ts
  src/commands/execution/index.ts
  src/commands/index.ts
Labels: enhancement, reviews: required

#16 Create readme draft
  README.md
Labels: reviews: required

#15 :sparkles: Insert header
  package-lock.json
  src/commands/insert_header/confgExample.json
  src/commands/insert_header/insert_header.ts
  src/commands/insert_header/types.ts
  tsconfig copy.json
Labels: reviews: approved

#17 [config] Default configuration object
  src/config/defaultConfig.ts
  src/constants/commitTypes.ts
  src/constants/emojis.ts
  src/constants/index.ts
  src/types/config.ts
Labels: feat: new, reviews: required, config

#20 [config] Update module system to ESM
  package.json
  pnpm-lock.yaml
  src/commands/execution/command.ts
  src/config/alias.ts
  src/config/loader.ts
  src/index.ts
  tsconfig.json
Labels: reviews: skip, config

#19 [config] Add default replace examples for dev
  src/config/defaultConfig.ts
  src/constants/index.ts
  src/constants/replaceExamples.ts
Labels: feat: new, reviews: required, config

#18 [commit] modify convert method
  pnpm-lock.yaml
  src/commands/insertHeader/insertHeader.test.ts
  src/commands/insertHeader/insertHeader.ts
  src/commands/insert_header/confgExample.json
  src/commands/insert_header/insert_header.ts
  src/commands/insert_header/types.ts
  src/types/commit.ts
Labels: reviews: required, feat: improve

#31 [config] Jest alias path setting
  package.json
  pnpm-lock.yaml
  test/index.spec.ts
Labels: reviews: skip, config

#29 [commit] insertHeader bug fix
  src/commands/insertHeader/insertHeader.ts
Labels: fix: bug

#26 [commit] Interactive cli inqueries
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/commands/commit/questions.ts
  src/config/defaultConfig.ts
  src/config/loader.ts
  src/constants/index.ts
  src/constants/scopeExamples.ts
  src/types/commit.ts
  src/utils/filterHeaders.ts
  tsconfig.json
Labels: reviews: required

#36 [commit] insertHeader test code
  src/commands/insertHeader/index.ts
  src/commands/insertHeader/insertHeader.test.ts
  test/commands/insertHeader/insertHeader.spec.ts
Labels: reviews: required, feat: improve

#40 [commit]:recycle: Refactor insertHeader method and write test code
  src/commands/insertHeader/insertHeader.ts
  test/commands/insertHeader/insertHeader.spec.ts
Labels: feat: improve

#38 [commit] read config
  gitoverc.json
  package.json
  pnpm-lock.yaml
  src/readConfig/getConfigfile.ts
  src/readConfig/index.ts
Labels: feat: new, reviews: required

#44 [docs] Update README, CONTRIBUTING, CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  assets/logo.png
Labels: documentation, reviews: required

#45 [commit] create issue templates and update PR template
  .github/ISSUE_TEMPLATE/bugReport.yml
  .github/ISSUE_TEMPLATE/featureRequest.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, reviews: required

#42 [config] Change transpiler to Babel and publish
  .gitignore
  .npmignore
  babel.config.json
  package.json
  pnpm-lock.yaml
  src/config/loader.ts
  src/types/index.ts
  tsconfig.json
Labels: reviews: required

#43 [commit] Created new feature: `replaceAliasToName`
  .husky/pre-commit.sh
  pnpm-lock.yaml
  src/commands/replace/replace.ts
  test/commands/replace/replace.spec.ts
Labels: feat: new, reviews: required

#48 [commit] Put commit features together in commitAction
  .eslintrc.json
  src/commands/commit/action.ts
  src/commands/commit/questions.ts
  src/commands/insertHeader/index.ts
  src/commands/insertHeader/insertHeader.ts
  src/config/defaultConfig.ts
  src/constants/commitTypes.ts
  src/readConfig/getConfigfile.ts
  src/types/commit.ts
  src/utils/filterHeaders.ts
  src/utils/index.ts
  src/utils/insertHeader.ts
  src/utils/replaceKeywords.ts
Labels: reviews: skip

#50 [commit] Validate and capitalize commit title
  package.json
  src/commands/commit/questions.ts
  src/utils/capitalizeTitle.ts
  src/utils/index.ts
  src/utils/insertHeader.ts
Labels: reviews: skip

#51 [commit] Update tests - CommitMessage type changed
  test/commands/insertHeader/insertHeader.spec.ts
  test/commands/replace/replace.spec.ts
  test/index.spec.ts
  test/utils/insertHeader.spec.ts
Labels: reviews: skip

#56 [commit] Add git wrap commit() to action.ts
  package.json
  pnpm-lock.yaml
  src/commands/commit/action.ts
  src/commands/index.ts
  src/utils/execution/command.ts
  src/utils/execution/gitWrap.ts
  src/utils/execution/index.ts
Labels: reviews: required, feat: improve

#59 :wrench: Configuring Dependabot
  .github/dependabot.yml
Labels: config

#54 :memo: Update issue template
  .github/ISSUE_TEMPLATE/bugReport.yml
  .github/ISSUE_TEMPLATE/featureRequest.yml
Labels: documentation, reviews: approved

#62 [docs] update readme.md
  README.md
Labels: documentation, reviews: required

#63 [commit] Print out commit result message
  src/commands/commit/action.ts
  src/utils/execution/command.ts
  src/utils/execution/gitWrap.ts
Labels: reviews: skip

#66 :bug: Npm install bug solved
  package.json
  pnpm-lock.yaml
Labels: reviews: skip, config

#67 [config] Fix getConfigFile dirname issue
  babel.config.json
  package.json
  pnpm-lock.yaml
  src/config/getConfigfile.ts
  src/config/index.ts
Labels: reviews: required, config
